version : '3'

services :
  api:

    build: backend/.

    volumes:
      - .:/app/
      - /app/node_modules/

    ports:
      - "9000:9000"

    
    env_file:
      - backend/.env
      
  angular: 

    build: client/.

    ports:
      - "4200:4200"